semantic:
  properties:
  - https://schema.undata.live/elements/channels_1lru4v
  - https://schema.undata.live/elements/coordinate_system_bgu223
  - https://schema.undata.live/elements/device_name_d95ria
  - https://schema.undata.live/elements/images_a7c0ho
  - https://schema.undata.live/elements/sampling_strategy_1lrzc6
  mixins: []
provenance:
- source: aind
  name: ImagingConfig
