semantic:
  data_type: object
  question_text: Device configuration
  source_attribute: device_config
  source_class: CatheterImplant
  type_ref: CatheterConfig
provenance:
- source: aind
  class: CatheterImplant
  name: device_config
  description: Configuration of a catheter
  generated_at: '2026-03-21T05:07:45.964026+00:00'
  attributed_to: urn:undata:ingestion-pipeline
  activity: ingestion
sha256: 4c05bc6055ae53f203d6b72c6e2b63f7a3f86d1849543b210ff577625400cf56
