semantic:
  data_type: array
  question_text: Training performance
  source_attribute: train_performance
  source_class: ModelTraining
provenance:
- source: aind
  class: ModelTraining
  name: train_performance
  description: Performance on training set
  generated_at: '2026-03-21T05:07:45.964026+00:00'
  attributed_to: urn:undata:ingestion-pipeline
  activity: ingestion
- source: aind
  class: ModelTraining
  name: train_performance
  description: Performance on training set
  generated_at: '2026-03-21T05:07:45.964026+00:00'
  attributed_to: urn:undata:ingestion-pipeline
  activity: ingestion
sha256: a309ae50b79dc6d1dffe397e2f5a31e1d2b45e02b70ee72d21d90a6b8e407ada
